services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./cmd/server/Dockerfile
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    environment:
      JWT_SECRET: ${JWT_SECRET}
      ACCESS_TOKEN_TTL: ${ACCESS_TOKEN_TTL}
      REFRESH_TOKEN_TTL: ${REFRESH_TOKEN_TTL}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_URI: mongodb://mongodb
      MONGO_DATABASE_NAME: go-token-auth
      REDIS_ADDRESS: redis:6379
      REDIS_SSL: ${REDIS_SSL}
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
